name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Меняем на нужную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Generate static files
        run: npm run generate
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuxt-dist
          path: .nuxt/dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish_dir: .nuxt/dist